gvr_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: GVRUserBundle:Default:index }

gvr_user_index:
    path:   /user/index
    defaults: { _controller: GVRUserBundle:User:index }
    
gvr_user_add:
    path:   /user/add
    defaults: { _controller: GVRUserBundle:User:add }
    
gvr_user_edit:
    path:   /user/edit/{id}
    defaults: { _controller: GVRUserBundle:User:edit }

gvr_user_view:
    path:   /user/view/{id}
    defaults: { _controller: GVRUserBundle:User:view }
    
gvr_user_delete:
    path:   /user/delete/{id}
    defaults: { _controller: GVRUserBundle:User:delete }